# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: v1.22.0
        kubernetes version: v1.20.7
        driver: docker
        start args: '--extra-config=etcd.initial-advertise-peer-urls http://0.0.0.0:9988 --extra-config=etcd.listen-peer-urls=http://0.0.0.0:9988 --extra-config=etcd.advertise-client-urls=http://0.0.0.0:9977 --extra-config=etcd.listen-client-urls=http://0.0.0.0:9977'
    - name: Interact with the cluster
      run: kubectl get nodes

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml
